print (" Hi! My name is Sophia Bot 2.0")
input ()
name= input ("What is your name?")
print (f"Hello {name} and welcome to SB 2.0, which stands for Sophia Bot 2.0")
input ()
print ("My main mission is to talk to you about you and how you are.")
input ()
print("Feel free to chat with me whenever you want.")
input ()
emotion  ("How are you doing today?")
