print (" Hi! My name is Sophia Bot 2.0")
input ()
name= input ("What is your name?")
print (f"Hello {name} and welcome to SB 2.0, which stands for Sophia Bot 2.0")
input ()
print ("My main mission is to talk to you about you and how you are.")
input ()
print("Feel free to chat with me whenever you want.")
input ()
emotion= input ("How are you doing today?")
print (f"Okay {emotion} thank you for sharing me, I am here for whatever you are feeling.")
input ()
skill= input ("What is a skill that you would like to learn?")
print (f"{skill}, nice! If you take the right steps you could master that skill faster.")
input ()
print ("Taking steps to reach a goal is a very smart idea, when you take steps to learn a skill, the sky's the limit. ")
input ()
goal= input ("What is your goal when you use a device/computer?")
print (f"Interesting. {goal} is a very adventurous goal.")
input ()
print ("Setting goals can help someone measure progress and increase motivation.")
input ()
print ("Thank you for talking with me today!")
input ()
print ("Remember I will always be here, so you can come back and chat anytime!")